# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

pod 'JSQMessagesViewController'
pod 'ALCameraViewController' 
pod 'SCLAlertView'
pod 'Firebase'
pod 'Firebase/Messaging’
pod 'Firebase/Database'
pod 'Firebase/DynamicLinks'
pod 'Firebase/Auth'
pod 'M13Checkbox'
pod 'LNRSimpleNotifications'

target 'Bartr' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bartr

  target 'BartrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BartrUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
